# Generated by Django 2.1.4 on 2019-02-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190211_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='secondary_telephone_no',
            new_name='mobile_no',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='telephone_no',
            new_name='secondary_mobile_no',
        ),
    ]
