# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPortfolioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=15)),
                ('middle', models.CharField(max_length=15, null=True)),
                ('last', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('second_email', models.EmailField(max_length=254, null=True)),
                ('other_email', models.EmailField(max_length=254, null=True)),
                ('profile', models.ImageField(null=True, upload_to='images')),
                ('tel', models.CharField(max_length=13)),
                ('facebook', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
                ('github', models.URLField(null=True)),
                ('bitbucket', models.URLField(null=True)),
                ('bio', models.TextField(null=True)),
                ('skills', models.TextField(null=True)),
                ('fav_quotes', models.TextField(null=True)),
                ('fun_facts', models.TextField(null=True)),
                ('projects', models.TextField(null=True)),
                ('likes', models.TextField(null=True)),
            ],
        ),
    ]
