# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfoliomodel',
            name='middle',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
